### PR TITLE
make editor always appear on top without being overlapped

### PR DESCRIPTION
**Pull request by Mackiovello**
This happens without:

capture

### CODE REVIEW

**Comment by tomalec** [comment]
Could you give steps to reproduce the issue?

Your solution makes the editor overlays the page. For example when run with products app, it appears on top (in z axis) of navigation manu, so the partial it's about to edit.

**Comment by Mackiovello** [comment]
Just create an element with the following CSS:

```css
.fixed-toolbar {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1;
}
```

**Comment by Mackiovello** [comment]
There is possibly a better solution, this was just the first one I thought of

**Comment by tomalec** [comment]
> Just create an element with the following CSS:
> 
> ```css
> .fixed-toolbar {
>     position: fixed;
>     top: 0;
>     left: 0;
>     z-index: 1;
> }
> ```

But above means you want your element to overlap the editor, so where is the problem?

**Comment by Mackiovello** [comment]
> But above means you want your element to overlap the editor, so where is the problem?

The problem is that you can't have a fixed header with the editor. When building an app, you'll probably not be thinking about how to prevent it from overlapping with the editor. It's not super important since you can just inspect the element and uncheck the `position: fixed` property to fix it. If you feel like this tradeoff is worth it, please close this PR.

**Comment by tomalec** [comment]
Maybe let's first decide how we would like the editor to be placed if there are any fixed or absolute positioned elements. This case may happen pretty often, so it's better to have fixed decision on it.

**Comment by warpech** [comment]
I assume that the problem on the original screenshot happens if the content from another app is absolutely positioned. Is that necessary? In my opinion absolutely positioned elements will never be nicely blendable.

**Comment by Mackiovello** [comment]
Yes, the element in the screenshot is the fixed toolbar from [MDC](https://material-components-web.appspot.com/toolbar/fixed-toolbar.html). The styling is:

```css
.mdc-toolbar--fixed {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 1;
}
```

> Is that necessary?

In my case, it's not. I imagine that there will be cases where other people want to use fixed toolbars etc.

**Comment by warpech** [comment]
> In my case, it's not. I imagine that there will be cases where other people want to use fixed toolbars etc.

For this, they can edit the `declarative-shadow-dom` in CompositionEditor and save that as a custom composition. That's the whole point of editing the default `declarative-shadow-dom`, which does not cover all of the world's use cases. It just provides a good-enough default that you can later edit. In this case, you would use CompositionEditor to edit CompositionEditor's view. 

The only problem is that right now `compositioneditor-panel` is inserted in a rather hacky way to `<body>`, because of the lack of https://github.com/Starcounter/level1/issues/4017. So for the time being, there is not much we can do :(

**Comment by Mackiovello** [comment]
Okay, thank you for the answers, closing.

**Pull request closed without merging**
