### PR TITLE
Fix for Content-Type header

### PR DESCRIPTION
**Pull request by warpech**
Solves #45

### CODE REVIEW

**Comment by alshakero** [comment]
Sorry to interfere, but isn't throwing this HTML inside /sys folder of `CompositonEditor' faster, better and more maintainable?

**Comment by warpech** [comment]
Hmm but this looks like something else. More similar to https://github.com/Starcounter/Home/issues/313. 

1. Do you get this always or sometimes?
2. Do you get this with Firefox addons disabled?

**Comment by un-tone** [comment]
I have a clean Firefox (today I tried with full clean reinstalled one). I'm getting an empty page each first time after running CompositionEditor. The same issue with Chrome.

Maybe something wrong with my environment. Let's ask someone else test the issue?

**Comment by warpech** [comment]
Merging this fix. Please make a new issue regarding the problem that you describe because it seems unrelated. I can't reproduce it but someone else may.

**Comment by warpech** [comment]
Merging this fix. Please make a new issue regarding the problem that you describe because it seems unrelated. I can't reproduce it but someone else may.

**Comment by un-tone** [comment]
Currently it works well on my computer too :-) .

**Pull request merged**
