### PR TITLE
Simplify SVG icon styles

### PR DESCRIPTION
**Pull request by warpech**
I have made SVG icon fixes according the what I discussed recently with @mmnosek.

The best practices are now described in: https://starcounter.gitbooks.io/guidelines/content/icons.html

@mmnosek could you please review this PR as well as the Gitbook page?

### CODE REVIEW

**Comment by mmnosek** [comment]
The code looks fine for me. Although, I'm wondering if it's fine that it looks a bit bad with current Launcher? Am I missing something?
launcher-composition-editor


Regarding the gitbook, shouldn't we:
- move reference example links to the bottom
- make them shorter

It looks overwhelming for me, especially at the beginning of the page.

**Comment by warpech** [comment]
The above 2 commits contain a fix for #5 as well as a fix for SVG styles in browsers other than Chrome.

**Comment by warpech** [comment]
In the Gitbook, I have edited the text to make it more approachable. @mmnosek is it better now?

**Comment by warpech** [comment]
Merged, thx for the review!

**Pull request merged**
